//
// Created by henry on 4/12/19.
//

#include "decode.h"
/**
 * Decode AVPackets into a AVFrame
 * @param dec_cts Decoder context used to decode the video
 * @param frame resulting frame generated by decoding the packet
 * @param ptk incoming packet to convert into a frame
 * @return Returns 1 on success, less than or equal to 0 is a failure
 */
int decode(AVCodecContext *dec_cts, AVFrame *frame, AVPacket *ptk){
    int ret;

    ret = avcodec_send_packet(dec_cts, ptk);
    if(ret < 0 ){
        char error_msg[1000];
        av_strerror(ret,error_msg, 1000);
        fprintf(stderr, "error sending a packet for decoding. Reason: %s\n", error_msg);
        return ret;
    }
    while (ret >=0){
        ret = avcodec_receive_frame(dec_cts, frame);
        if(ret == AVERROR(EAGAIN) || ret == AVERROR_EOF){
            return ret;
        } else if (ret < 0){
            fprintf(stderr, "error During decoding\n");
            return ret;
        }


        return 1;
    }
    char error_msg[1000];
    av_strerror(ret,error_msg, 1000);
    fprintf(stderr, "error . Reason: %s\n", error_msg);
    exit(1);

}