FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y software-properties-common wget

# RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add && \
#     apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - && \
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

RUN apt-get update && apt-get install -y build-essential \
    python3-pip \
    cmake \
    mesa-common-dev:amd64 \
    libgbm-dev:amd64 \
    libasound2-dev:amd64 \
    libjack-dev:amd64 \
    libpulse-dev:amd64 \
    autoconf \
    automake \
    libtool \
    libsdl2-dev \
    libegl1-mesa-dev:amd64 \
    libaudio-dev:amd64 \
    libxcursor-dev:amd64 \
    libxinerama-dev:amd64 \
    libxi-dev:amd64 \
    libxrandr-dev:amd64 \
    libxss-dev:amd64 \
    libvdpau-dev:amd64 \
    libva-dev:amd64 \
    libxcb-shm0-dev:amd64 \
    libcap-dev \
    libavcodec-dev \
    libavdevice-dev \
    libavfilter-dev \
    libavformat-dev \
    libavresample-dev \
    libavutil-dev \
    libswresample-dev \
    libswscale-dev \
    doxygen \
    python3-all-dev \
    python3-venv \
    cppcheck \
    python3 \
    python3-wheel \
    python3.7-venv \
    clang-tidy \
    clang-tidy-7 \
    libclang-common-7-dev \
  && rm -rf /var/lib/apt/lists/*

ENV CONAN_NON_INTERACTIVE=1

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN python3 -m pip install --upgrade pip && python3 -m pip install conan

RUN groupadd -g $GROUP_ID user && \
    useradd -u $USER_ID -s /bin/sh -m -d /home/user -g user user

COPY ci/dockerfiles/conan/remotes.json /home/user/.conan/remotes.json
ENV CONAN_USER_HOME=/home/user/

COPY ci/dockerfiles/conan/profiles/ /home/user/.conan/profiles/
ENV CONAN_DEFAULT_PROFILE_PATH=/home/user/.conan/profiles/x64


ADD conanfile.py /tmp/
RUN conan install /tmp/ --no-imports --build sdl2 --build ffmpeg && conan remove --locks -f
RUN chown -R user:user /home/user/.conan/
