set(CPACK_PACKAGE_NAME "Visvid")
set(CPACK_PACKAGE_VENDOR "Henry Borchers")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/license.txt")
set(CPACK_COMPONENT_LIBVISVID_REQUIRED TRUE)

set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Create Visual")
set(CPACK_PACKAGE_EXECUTABLES CreateVisual "Test Visualzations")
#set(CPACK_SOURCE_INSTALLED_DIRECTORIES
#        "${PROJECT_SOURCE_DIR}/examples;/examples"
#        "${PROJECT_SOURCE_DIR}/src;/src"
#        "${PROJECT_SOURCE_DIR}/tests;/tests"
#        "${PROJECT_SOURCE_DIR}/docs;/docs"
#        )
#set(CPACK_SOURCE_STRIP_FILES TRUE)
#set(CPACK_IGNORE_FILES ${PROJECT_SOURCE_DIR}/venv)
#list(APPEND CPACK_IGNORE_FILES ${PROJECT_SOURCE_DIR}/venv)
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\\\.svn/;/\\\\.bzr/;/\\\\.hg/;/\\\\.git/;\\\\.swp\\$;\\\\.#;/#")
list(APPEND CPACK_SOURCE_IGNORE_FILES /\\\\.idea)
list(APPEND CPACK_SOURCE_IGNORE_FILES /venv)
list(APPEND CPACK_SOURCE_IGNORE_FILES /_CPack_Packages)
list(APPEND CPACK_SOURCE_IGNORE_FILES /install)
list(APPEND CPACK_SOURCE_IGNORE_FILES \\\\.gitmodules)
list(APPEND CPACK_SOURCE_IGNORE_FILES \\\\.gitignore)
list(APPEND CPACK_SOURCE_IGNORE_FILES Jenkinsfile)
list(APPEND CPACK_SOURCE_IGNORE_FILES visvid.kdev4)
list(APPEND CPACK_SOURCE_IGNORE_FILES plugins.txt)
list(APPEND CPACK_SOURCE_IGNORE_FILES Dockerfile)

file(RELATIVE_PATH BUILD_PATH_NAME  ${PROJECT_SOURCE_DIR} ${PROJECT_BINARY_DIR})
list(APPEND CPACK_SOURCE_IGNORE_FILES /cmake-build-debug)
list(APPEND CPACK_SOURCE_IGNORE_FILES /${BUILD_PATH_NAME})
