set(CPACK_PACKAGE_NAME "Visvid")
set(CPACK_PACKAGE_VENDOR "Henry Borchers")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/license.txt")
set(CPACK_COMPONENT_LIBVISVID_REQUIRED TRUE)

set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Create Visual")
set(CPACK_PACKAGE_EXECUTABLES CreateVisual "Test Visualzations")