# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install libsdl2-dev \
                         libavcodec-dev \
                        libavdevice-dev \
                        libavfilter-dev \
                        libavformat-dev \
                        libavresample-dev \
                        libavutil-dev \
                        libswresample-dev \
                        libswscale-dev \
                        doxygen
    - name: Run CMake
      run: |
        cmake -B ./build -S ./ -D CMAKE_C_FLAGS="-Wall -Wextra" -D CMAKE_CXX_FLAGS="-Wall -Wextra" -D libvisvid_TESTS:BOOL=ON
        cmake --build ./build --target all --target test-visvid --target test-visvid-internal
    - name: Run CTest
      run: cd build && ctest
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Get sonarscanner
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          export PATH=${PWD}/wrapper-linux-x86:$PATH

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
